# Generated by Django 3.2.15 on 2022-08-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('std_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
